package org.hexmonad.msc2gen;

import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.HashMap;

import org.antlr.runtime.*;
import org.antlr.runtime.tree.*;

public class MscParser {
    private PrintStream outStream;
    private ArrayList<String> lifelines = new ArrayList<String>();
    private boolean instFlag = true;    // true while parsing of instance declarations
    
    // contains tuple (message name --> message sender name)
    private HashMap<String, String> msgSender = new HashMap<String, String>();
    private HashMap<String, String> msgReceiver = new HashMap<String, String>();

    public void parse(String mscFileName, String outFileName) throws IOException, RecognitionException {
        ANTLRFileStream char_stream = new ANTLRFileStream( mscFileName );
        msc_grammarLexer lexer = new msc_grammarLexer( char_stream );
        CommonTokenStream tokens = new CommonTokenStream( lexer );
        
        msc_grammarParser parser = new msc_grammarParser( tokens );
        CommonTree tree = (CommonTree) parser.messageSequenceChart().getTree();
        System.out.println(tree.toStringTree());
        
        // get MSC name
        String mscName = tree.getChild(0).getChild(0).toString();
        outFileName = ( outFileName == null ? mscName + ".mscin" : outFileName );
        
        outStream = new PrintStream(outFileName);
        outStream.println("# This file was generated by msc2gen tool.");
        outStream.println("msc {");
        
        //parse MSC Body only
        parseTree( tree.getChild(1), null, "    " );
        
        outStream.print("}");
        outStream.close();
    }
    
    private void parseTree(Tree tree, String lifeline, String indentLevel) {
        String token = tree.getText();
        
        if (token.equals("MSCBody")) {
            parseChildTree(tree, lifeline, indentLevel);
            
        } else if (token.equals("Instance")) {
            String instName = tree.getChild(0).getText();
            
            if (tree.getChild(1).getText().equals("instance")) {
                String commaSign = ( lifelines.isEmpty() ? "" : ", " );
                outStream.print(commaSign + instName);
                lifelines.add(instName);
            } else if (instFlag) {
                // end of instance declarations
                outStream.println(";\n");
                instFlag = false;
            }
            parseChildTree(tree, instName, indentLevel);
        
        } else if (token.equals("MSGIn")) {
            String msg = tree.getChild(0).getText().replaceAll("^\'|\'$", "");
            
            if (tree.getChild(1).getText().equals("MsgGate")) {                 // message input from ENV
                outStream.println(lifeline + " note " + lifeline + " [label=\"from_env{ " + msg + " }\"];");
            
            } else if (msgSender.get(msg) != null) {
                outStream.println(msgSender.get(msg) + "->" + lifeline + " [label=\"" + msg + "\"];");
                msgSender.put(msg, null);
            
            } else {
                msgReceiver.put(msg, lifeline);
            }
            
        } else if (token.equals("MSGOut")) {
            String msg = tree.getChild(0).getText().replaceAll("^\'|\'$", "");
            String receiver = tree.getChild(1).getText();
            
            if (receiver.equals("MsgGate")) {                 // message output to ENV
                outStream.println(lifeline + " note " + lifeline + " [label=\"to_env{ " + msg + " }\"];");
            
            } else if (tree.getChild(2).getText().equals("IncompleteMsg")) {    // lost of message
                outStream.println(lifeline + "-x" + receiver + " [label=\"" + msg + "\"];");
            
            } else if (msgReceiver.get(msg) != null) {
                outStream.println(lifeline + "->" + msgReceiver.get(msg) + " [label=\"" + msg + "\"];");
                msgReceiver.put(msg, null);
            
            } else {
                msgSender.put(msg, lifeline);
            }
        
        } else if (token.equals("Action")) {
            String text = tree.getChild(0).getText().replaceAll("^\'|\'$", "");
            outStream.println(lifeline + " box " + lifeline + " [label=\"" + text + "\"];");
        }
    }
    
    private void parseChildTree(Tree tree, String lifeline, String indentLevel) {
        int num = tree.getChildCount();
        for(int i = 0; i < num; i++) {
            parseTree(tree.getChild(i), lifeline, indentLevel);
        }
    }
}
